export { FeaturedProjects } from "./featured-projects";
export { ProjectGallery } from "./project-gallery";
export { Categories } from "./categories";
export { Awards } from "./awards";
export { ProjectDetailHeader } from "./project-detail-header";
export { BeforeAfter } from "./before-after";
export { RelatedProjects } from "./related-projects";
export { ProjectCategories } from "./project-categories";
export { Awards as ProjectAwards } from "./awards";
export { StatisticsShowcase as ProjectStatistics } from "../statistics/statistics-showcase";
