export const ADMIN_PATHS = {
  LOGIN: "/admin/login",
  DASHBOARD: "/admin",
  PROJECTS: "/admin/projects",
  PROJECT_NEW: "/admin/projects/new",
  PROJECT_EDIT: (id: string) => `/admin/projects/${id}`,
  SERVICES: "/admin/services",
  SERVICE_NEW: "/admin/services/new",
  SERVICE_EDIT: (id: string) => `/admin/services/${id}`,
  BLOG: "/admin/blog",
  BLOG_NEW: "/admin/blog/new",
  BLOG_EDIT: (id: string) => `/admin/blog/${id}`,
  TEAM: "/admin/team",
  TEAM_NEW: "/admin/team/new",
  TEAM_EDIT: (id: string) => `/admin/team/${id}`,
  TESTIMONIALS: "/admin/testimonials",
  FAQ: "/admin/faq",
  PRICING: "/admin/pricing",
  GALLERY: "/admin/gallery",
  MEDIA: "/admin/media",
  NAVIGATION: "/admin/navigation",
  CAREER: "/admin/career",
  CAREER_NEW: "/admin/career/new",
  CAREER_EDIT: (id: string) => `/admin/career/${id}`,
  FORMS: "/admin/forms",
  NEWSLETTER: "/admin/newsletter",
  PAGES: "/admin/pages",
  REDIRECTS: "/admin/redirects",
  SETTINGS: "/admin/settings",
  PROFILE: "/admin/profile",
} as const;
